[workspace]
authors = ["Peter Alexander <makeroftools@creativedevelopment.systems>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]
build = "cargo build"
start = "cargo run"
test = "cargo test"
clean = "cargo clean"
fmt = "cargo fmt"
lint = { cmd = "cargo clippy", depends-on = ["fmt"] }
bench = "cargo bench"

[dependencies]
rust = ">=1.90.0,<1.91"

[package]
name = "cbp-gateway"
version = "0.1.0"

[package.build]
backend = { name = "pixi-rust", version = "0.0.0"}

[package.build.config]
extra-args = ["Blah"]
